// <auto-generated />
using System;
using Ecommerce.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecommerce.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429204041_FinalizarEntidadesBase")]
    partial class FinalizarEntidadesBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Domain.Entities.Auditoria", b =>
                {
                    b.Property<int>("id_auditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_auditoria"));

                    b.Property<string>("accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("datos_anteriores")
                        .HasColumnType("text");

                    b.Property<string>("datos_nuevos")
                        .HasColumnType("text");

                    b.Property<DateTime>("fe_evento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("registro_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tabla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_auditoria");

                    b.ToTable("gn_auditoria", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_categoria"));

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("es_activo")
                        .HasColumnType("boolean");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_categoria");

                    b.ToTable("pr_categoria", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_cliente"));

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("direccion")
                        .HasColumnType("text");

                    b.Property<bool>("es_activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fe_creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("identificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telefono")
                        .HasColumnType("text");

                    b.HasKey("id_cliente");

                    b.ToTable("gn_cliente", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("id_producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_producto"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("precio")
                        .HasColumnType("numeric");

                    b.Property<int>("stock")
                        .HasColumnType("integer");

                    b.HasKey("id_producto");

                    b.ToTable("pr_producto", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("id_rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_rol"));

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_rol");

                    b.ToTable("sc_rol", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_usuario"));

                    b.Property<int?>("Rolid_rol")
                        .HasColumnType("integer");

                    b.Property<string>("clave_hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("es_activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fe_creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("id_rol")
                        .HasColumnType("integer");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_usuario");

                    b.HasIndex("Rolid_rol");

                    b.ToTable("sc_usuario", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Ecommerce.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("Rolid_rol");

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
